[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Environment variables for functions
[context.production.environment]
  # GEMINI_API_KEY will be set in Netlify dashboard

[context.deploy-preview.environment]
  # GEMINI_API_KEY will be set in Netlify dashboard

[functions]
  node_bundler = "esbuild"